Updates to include Scala Native 0.5.0
scalameta/metaconfig pull request #188
Opened 2024-04-16 18:21 UTC by ekrich

- [ ] Waiting on https://github.com/typelevel/paiges/issues/615

2024-04-16 18:22 UTC, ekrich commented
Do we want to update Scala.js to the latest?

2024-04-17 08:02 UTC, tgodzik commented
> Do we want to update Scala.js to the latest?

I think that's fine, though probably in a separate PR?

2024-04-17 15:12 UTC, ekrich commented
Oh, I was trying to update everything like `sbt-ci-release` and other things. I can back off and just touch what needs to be updated or all at once which I think might be better.

2024-04-17 15:20 UTC, tgodzik commented
> Oh, I was trying to update everything like `sbt-ci-release` and other things. I can back off and just touch what needs to be updated or all at once which I think might be better. `sbt-native-packager` is a weird one because of release problems so not sure on that one.

it would probably be better one by one, but I wonder why it didn't happen via steward

2024-04-17 15:21 UTC, ekrich commented
Ok, I will just back off to do only the required upgrades.

2024-04-17 15:24 UTC, tgodzik commented
Ok, added metaconfig to the repo, that should help in this case. We can wait for the updates to show up, I just run the workflow

2024-04-17 15:54 UTC, ekrich commented
That is great thanks - those can all go through as I wait.

2024-04-17 16:25 UTC, ekrich commented
@tgodzik I will go ahead and rebase when all the updates get merged.

2024-06-18 14:26 UTC, tgodzik requested changes
Awesome! It's finally passing :tada: 

We can just update paiges to latest version and merge.

2024-06-18 14:26 UTC, tgodzik commented on build.sbt
> +      "org.typelevel" %%% "paiges-core" % "0.4.3-35-4d6217a-SNAPSHOT",
Looks like we can switch to 0.4.4 ?

2024-06-18 15:21 UTC, ekrich commented on build.sbt
> +      "org.typelevel" %%% "paiges-core" % "0.4.3-35-4d6217a-SNAPSHOT",
Updated waiting for CI to pass.

2024-06-18 15:58 UTC, merged

2024-06-18 15:59 UTC, tgodzik commented
Should we do a new release?

2024-06-18 16:13 UTC, ekrich commented
I wanted to update this in case someone ever gets back to trying to port the Scala Native `scalafmt`. We have multi-threading now so there could be less changes. The diff(ing) part was asked to be a separate project which seemed to be the biggest part of the angst of the large change.

2024-06-18 16:15 UTC, tgodzik commented
Och yeah, I did release it separate because of that. I need to return to the PR :|

2024-06-18 18:49 UTC, ekrich commented
> Och yeah, I did release it separate because of that.

Do you have a link - we might be able to use it in Scala Native for our tools which we are trying to port to Scala Native as part of a potential "native" tool chain.

2024-06-18 18:58 UTC, tgodzik commented
We release is alognside munit https://mvnrepository.com/artifact/org.scalameta/munit-diff